[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "chromium"]

[phases.install]
cmds = [
  "python3 -m ensurepip --upgrade",
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt",
  "python3 -m playwright install chromium"
]

[phases.build]
cmds = []

[start]
cmd = "python3 -m uvicorn app.main:app --host 0.0.0.0 --port $PORT"
